# Generated by Django 4.2.11 on 2024-03-08 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cursos", "0002_alter_avaliacao_options_alter_curso_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="avaliacao",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="avaliacao",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="avaliacao",
            unique_together={("user", "curso")},
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="email",
        ),
        migrations.RemoveField(
            model_name="avaliacao",
            name="nome",
        ),
    ]
