# Generated by Django 4.2.11 on 2024-03-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0007_alter_avaliacao_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="media_avaliacoes",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
